-- Seed data for IA Lucrativa: biblioteca de prompts, ferramentas e desafio de 7 dias.
-- Dollar-quoting com a tag $t$ é usado em todos os valores de texto para evitar
-- problemas de escaping com apóstrofos do português.

-- =========================================================
-- Parte 1: Biblioteca de prompts
-- =========================================================
insert into public.prompts (title, description, category, content) values
-- Instagram
($t$Criar legenda para Instagram$t$, $t$Gera uma legenda envolvente para uma publicação no Instagram.$t$, $t$Instagram$t$, $t$Você é um especialista em criação de conteúdo. Escreva uma legenda para Instagram sobre [assunto], direcionada para [público]. O objetivo é [objetivo]. Utilize um tom [tom de voz], escreva até [quantidade] palavras e finalize com uma chamada para ação.$t$),
($t$Criar bio para perfil do Instagram$t$, $t$Ajuda a escrever uma bio curta e atrativa para o perfil do Instagram.$t$, $t$Instagram$t$, $t$Você é um especialista em marketing digital. Crie uma bio para Instagram para [nome do perfil ou marca], que atua em [área/nicho]. A bio deve transmitir [características/valores], atrair [público-alvo] e ter no máximo [quantidade] caracteres. Inclua uma chamada para ação no final.$t$),
($t$Planejar cronograma de posts para Instagram$t$, $t$Cria um calendário de postagens para a semana ou mês.$t$, $t$Instagram$t$, $t$Você é um especialista em planejamento de conteúdo para redes sociais. Crie um cronograma de postagens para Instagram para [período de tempo], para um perfil sobre [tema/nicho]. Inclua sugestões de tema para cada dia, formato (foto, carrossel, reels) e horário ideal de publicação, considerando que o público é [público-alvo].$t$),
-- Reels e TikTok
($t$Criar roteiro para Reels$t$, $t$Monta um roteiro estruturado para um vídeo curto de Reels ou TikTok.$t$, $t$Reels e TikTok$t$, $t$Você é um especialista em vídeos curtos para redes sociais. Crie um roteiro para um Reels ou vídeo do TikTok sobre [assunto], com duração de até [quantidade] segundos. O roteiro deve ter um gancho nos primeiros 3 segundos, desenvolver a ideia de forma [tom de voz] e terminar com uma chamada para ação, pensando no público [público].$t$),
($t$Gerar ideias de vídeos virais$t$, $t$Sugere ideias de vídeos curtos com potencial de engajamento.$t$, $t$Reels e TikTok$t$, $t$Você é um especialista em conteúdo viral para redes sociais. Sugira [quantidade] ideias de vídeos curtos para Reels ou TikTok sobre [tema/nicho], voltados para [público-alvo]. Para cada ideia, explique o gancho inicial, o desenvolvimento e a chamada para ação.$t$),
($t$Criar legenda para Reels/TikTok$t$, $t$Escreve uma legenda curta e chamativa para acompanhar um vídeo curto.$t$, $t$Reels e TikTok$t$, $t$Você é um especialista em criação de conteúdo para redes sociais. Escreva uma legenda curta e chamativa para um vídeo de Reels ou TikTok sobre [assunto], destinado a [público]. O tom deve ser [tom de voz] e a legenda deve incentivar [objetivo, ex: comentários, compartilhamentos].$t$),
-- Legendas
($t$Criar legenda para foto de produto$t$, $t$Escreve uma legenda de vendas para uma foto de produto.$t$, $t$Legendas$t$, $t$Você é um especialista em copywriting para redes sociais. Escreva uma legenda para uma foto do produto [nome do produto], destacando [principais benefícios], voltada para [público-alvo]. Use um tom [tom de voz] e finalize com uma chamada para ação.$t$),
($t$Criar legendas com storytelling$t$, $t$Cria uma legenda que conta uma pequena história para conectar com o público.$t$, $t$Legendas$t$, $t$Você é um especialista em storytelling para redes sociais. Escreva uma legenda contando uma pequena história sobre [situação/experiência], relacionada ao tema [assunto], para o público [público-alvo]. A legenda deve emocionar e terminar conectando a história com uma chamada para ação sobre [objetivo].$t$),
-- Produtos digitais
($t$Gerar ideias de produtos digitais$t$, $t$Sugere ideias de produtos digitais para vender online.$t$, $t$Produtos digitais$t$, $t$Você é um especialista em produtos digitais. Sugira [quantidade] ideias de produtos digitais (como e-books, cursos, planilhas ou templates) sobre o tema [tema/nicho], voltados para [público-alvo] que deseja resolver o problema de [dor/problema].$t$),
($t$Criar descrição de venda para produto digital$t$, $t$Escreve o texto de vendas para a página de um produto digital.$t$, $t$Produtos digitais$t$, $t$Você é um especialista em copywriting de vendas. Escreva uma descrição de venda para o produto digital [nome do produto], que ensina/entrega [benefício principal], voltado para [público-alvo]. Destaque [diferenciais], use um tom [tom de voz] e finalize com uma chamada para ação para a compra.$t$),
($t$Criar estrutura para um produto digital$t$, $t$Monta o sumário/estrutura de módulos de um produto digital.$t$, $t$Produtos digitais$t$, $t$Você é um especialista em criação de infoprodutos. Crie uma estrutura (sumário) para um produto digital sobre [tema], com [quantidade] módulos ou capítulos, voltado para [público-alvo] que tem como objetivo [resultado desejado]. Para cada módulo, escreva um título e uma breve descrição.$t$),
-- E-books
($t$Criar sumário de e-book$t$, $t$Gera o sumário completo de um e-book a partir de um tema.$t$, $t$E-books$t$, $t$Você é um especialista em criação de conteúdo digital. Crie um sumário completo para um e-book sobre [tema], destinado a [público-alvo], com aproximadamente [quantidade] capítulos. Cada capítulo deve ter um título atrativo e uma breve descrição do que será abordado.$t$),
($t$Escrever introdução de e-book$t$, $t$Escreve a introdução que engaja o leitor logo nas primeiras páginas.$t$, $t$E-books$t$, $t$Você é um especialista em redação de e-books. Escreva a introdução de um e-book sobre [tema], destinado a [público-alvo]. A introdução deve apresentar o problema que o leitor enfrenta, mostrar que o e-book tem a solução e despertar o interesse para continuar a leitura, em um tom [tom de voz].$t$),
($t$Criar título e subtítulo para e-book$t$, $t$Sugere opções de título e subtítulo chamativos para um e-book.$t$, $t$E-books$t$, $t$Você é um especialista em marketing editorial. Crie [quantidade] opções de título e subtítulo para um e-book sobre [tema], voltado para [público-alvo], que deseja alcançar [objetivo/benefício]. Os títulos devem ser chamativos e despertar curiosidade.$t$),
-- Prestação de serviços
($t$Criar proposta de serviço$t$, $t$Escreve uma proposta comercial completa para um cliente.$t$, $t$Prestação de serviços$t$, $t$Você é um especialista em propostas comerciais. Escreva uma proposta de prestação de serviço de [tipo de serviço] para o cliente [nome ou tipo de cliente], explicando o escopo do trabalho, os prazos de [quantidade] dias e os benefícios de contratar esse serviço. Use um tom [tom de voz].$t$),
($t$Criar descrição de serviço para divulgação$t$, $t$Escreve um texto para divulgar um serviço em redes sociais ou site.$t$, $t$Prestação de serviços$t$, $t$Você é um especialista em marketing de serviços. Escreva uma descrição para divulgar o serviço de [tipo de serviço], destacando [principais benefícios], voltada para [público-alvo]. Inclua uma chamada para ação para agendar ou solicitar orçamento.$t$),
-- Produtividade
($t$Criar lista de tarefas priorizadas$t$, $t$Organiza uma lista de tarefas por ordem de prioridade.$t$, $t$Produtividade$t$, $t$Você é um especialista em produtividade. Organize a lista de tarefas a seguir por ordem de prioridade, considerando urgência e importância: [colar lista de tarefas]. Explique brevemente por que cada tarefa recebeu essa prioridade.$t$),
($t$Criar rotina diária produtiva$t$, $t$Monta uma rotina diária equilibrada entre trabalho e pausas.$t$, $t$Produtividade$t$, $t$Você é um especialista em gestão do tempo. Crie uma rotina diária para uma pessoa que trabalha com [profissão/atividade] e tem como objetivo [objetivo], considerando que ela tem disponível [quantidade] horas por dia. Inclua horários para trabalho, pausas e tarefas importantes.$t$),
($t$Resumir texto longo em pontos principais$t$, $t$Transforma um texto longo em um resumo objetivo em tópicos.$t$, $t$Produtividade$t$, $t$Você é um especialista em síntese de informações. Resuma o texto a seguir em até [quantidade] pontos principais, de forma clara e objetiva: [colar texto].$t$),
-- Organização
($t$Criar planilha de controle financeiro pessoal$t$, $t$Sugere a estrutura de uma planilha simples de finanças pessoais.$t$, $t$Organização$t$, $t$Você é um especialista em organização financeira. Sugira uma estrutura de planilha para controle financeiro pessoal, com colunas para [categorias de gastos], que ajude [público-alvo] a organizar receitas e despesas mensais de forma simples.$t$),
($t$Criar checklist de organização$t$, $t$Gera um checklist prático para organizar uma área da vida.$t$, $t$Organização$t$, $t$Você é um especialista em organização pessoal. Crie um checklist completo para organizar [área da vida, ex: casa, trabalho, finanças], com passos práticos e em ordem lógica, pensando em uma pessoa com pouco tempo disponível.$t$),
-- Atendimento
($t$Criar respostas para perguntas frequentes$t$, $t$Prepara respostas prontas para as dúvidas mais comuns dos clientes.$t$, $t$Atendimento$t$, $t$Você é um especialista em atendimento ao cliente. Crie respostas claras e educadas para as seguintes perguntas frequentes sobre [produto/serviço]: [listar perguntas]. Use um tom [tom de voz] e mantenha as respostas objetivas.$t$),
($t$Responder reclamação de cliente$t$, $t$Escreve uma resposta empática para lidar com um cliente insatisfeito.$t$, $t$Atendimento$t$, $t$Você é um especialista em atendimento ao cliente. Escreva uma resposta empática e profissional para um cliente insatisfeito com [motivo da reclamação], relacionado ao produto/serviço [nome]. A resposta deve reconhecer o problema, oferecer uma solução e manter um tom [tom de voz].$t$),
($t$Criar mensagem de boas-vindas para novos clientes$t$, $t$Cria uma mensagem inicial para receber quem acabou de comprar.$t$, $t$Atendimento$t$, $t$Você é um especialista em relacionamento com clientes. Escreva uma mensagem de boas-vindas para um novo cliente que acabou de adquirir [produto/serviço], explicando os próximos passos e reforçando o suporte disponível, em um tom [tom de voz].$t$),
-- Pesquisa de público
($t$Criar perguntas para pesquisa de público$t$, $t$Gera perguntas para entender melhor as dores e desejos do público.$t$, $t$Pesquisa de público$t$, $t$Você é um especialista em pesquisa de mercado. Crie [quantidade] perguntas para uma pesquisa com o objetivo de entender melhor o público [público-alvo] sobre o tema [tema/produto], identificando dores, desejos e comportamentos de compra.$t$),
($t$Criar persona do cliente ideal$t$, $t$Monta uma persona detalhada com base em informações do público.$t$, $t$Pesquisa de público$t$, $t$Você é um especialista em marketing e comportamento do consumidor. Com base nas informações a seguir: [colar informações sobre o público], crie uma persona detalhada do cliente ideal, incluindo idade, objetivos, dores, hábitos e como o produto/serviço [nome] pode ajudar essa pessoa.$t$),
-- Vendas
($t$Criar script de vendas$t$, $t$Monta um roteiro de apresentação para vender um produto ou serviço.$t$, $t$Vendas$t$, $t$Você é um especialista em vendas. Crie um script de vendas para apresentar o produto/serviço [nome], destacando [principais benefícios], para o público [público-alvo]. O script deve incluir abertura, apresentação do problema, solução, e fechamento com chamada para ação.$t$),
($t$Responder objeções de vendas$t$, $t$Cria argumentos persuasivos para contornar objeções comuns de clientes.$t$, $t$Vendas$t$, $t$Você é um especialista em vendas consultivas. Crie respostas persuasivas para as seguintes objeções de clientes sobre o produto/serviço [nome]: [listar objeções, ex: preço alto, não tenho tempo]. Use um tom [tom de voz] e argumentos baseados em valor.$t$),
($t$Criar mensagem de follow-up de vendas$t$, $t$Escreve uma mensagem de retomada de contato com um cliente interessado.$t$, $t$Vendas$t$, $t$Você é um especialista em vendas. Escreva uma mensagem de follow-up para um cliente que demonstrou interesse no produto/serviço [nome], mas ainda não finalizou a compra. A mensagem deve reforçar o valor da oferta e incluir uma chamada para ação, em um tom [tom de voz].$t$),
-- Planejamento
($t$Criar plano de ação para atingir uma meta$t$, $t$Divide uma meta em etapas concretas com prazos.$t$, $t$Planejamento$t$, $t$Você é um especialista em planejamento estratégico. Crie um plano de ação para atingir a meta de [meta/objetivo] em [prazo], considerando que a pessoa tem disponível [recursos/tempo]. Divida o plano em etapas com prazos específicos.$t$),
($t$Criar planejamento de conteúdo mensal$t$, $t$Monta um calendário de conteúdo para o mês inteiro.$t$, $t$Planejamento$t$, $t$Você é um especialista em planejamento de conteúdo. Crie um planejamento mensal de conteúdo sobre o tema [tema/nicho], para ser publicado em [rede social ou canal], com sugestões de temas para cada semana, pensando no público [público-alvo].$t$),
-- Educação
($t$Criar plano de aula$t$, $t$Estrutura uma aula completa sobre um tema específico.$t$, $t$Educação$t$, $t$Você é um especialista em educação. Crie um plano de aula sobre o tema [assunto], para alunos de [nível/idade], com duração de [quantidade] minutos. Inclua objetivo da aula, atividades práticas e uma forma de avaliar o aprendizado.$t$),
($t$Explicar um assunto de forma simples$t$, $t$Traduz um tema complexo em uma explicação fácil de entender.$t$, $t$Educação$t$, $t$Você é um especialista em ensinar de forma simples e didática. Explique o assunto [tema] como se estivesse falando com alguém que não tem nenhum conhecimento prévio sobre o assunto, usando exemplos do dia a dia e uma linguagem [tom de voz].$t$),
($t$Criar exercícios sobre um tema$t$, $t$Gera exercícios com diferentes níveis de dificuldade e gabarito.$t$, $t$Educação$t$, $t$Você é um especialista em criação de material didático. Crie [quantidade] exercícios sobre o tema [assunto], voltados para alunos de [nível/idade], com diferentes níveis de dificuldade e as respectivas respostas.$t$),
-- Currículos e carreira
($t$Melhorar currículo$t$, $t$Revisa e aprimora um currículo para uma vaga específica.$t$, $t$Currículos e carreira$t$, $t$Você é um especialista em recursos humanos e recrutamento. Revise e melhore o currículo a seguir para a vaga de [cargo/área], destacando as experiências e habilidades mais relevantes: [colar currículo]. Sugira também melhorias na organização e clareza do texto.$t$),
($t$Escrever carta de apresentação$t$, $t$Cria uma carta de apresentação personalizada para uma candidatura.$t$, $t$Currículos e carreira$t$, $t$Você é um especialista em processos seletivos. Escreva uma carta de apresentação para a vaga de [cargo], na empresa [nome da empresa ou tipo de empresa], destacando as qualidades de [principais qualificações] e o interesse genuíno pela oportunidade, em um tom [tom de voz].$t$);

-- =========================================================
-- Parte 2: Ferramentas
-- =========================================================
insert into public.tools (name, description, use_cases, difficulty, free_version, category, external_url, precautions) values
($t$ChatGPT$t$, $t$Assistente de IA da OpenAI para conversar, escrever, tirar dúvidas e gerar ideias em texto.$t$, $t$Escrever e revisar textos, responder perguntas, resumir conteúdos, gerar ideias, criar roteiros e ajudar em tarefas do dia a dia.$t$, 'iniciante', true, 'texto', $t$https://chat.openai.com$t$, $t$Sempre confira informações importantes antes de usar, pois a IA pode cometer erros ou apresentar dados desatualizados. Evite compartilhar dados pessoais sensíveis ou de terceiros nas conversas.$t$),
($t$Gemini$t$, $t$Assistente de IA do Google, integrado a diversos produtos como Gmail e Google Docs, usado para conversar, pesquisar e criar conteúdo.$t$, $t$Responder perguntas, pesquisar informações atualizadas, ajudar a escrever e-mails e textos, resumir documentos e apoiar tarefas de estudo e trabalho.$t$, 'iniciante', true, 'texto', $t$https://gemini.google.com$t$, $t$Verifique as informações geradas antes de tomar decisões importantes, principalmente dados numéricos ou factuais. Evite inserir informações confidenciais da empresa ou de clientes.$t$),
($t$Claude$t$, $t$Assistente de IA da Anthropic, focado em conversas longas, análise de textos e geração de conteúdo com atenção a segurança e ética.$t$, $t$Escrever e revisar textos, analisar documentos extensos, resumir conteúdos, tirar dúvidas e apoiar tarefas de organização e planejamento.$t$, 'iniciante', true, 'texto', $t$https://claude.ai$t$, $t$Revise sempre os textos gerados antes de publicar ou enviar, e não insira dados sensíveis ou confidenciais nas conversas.$t$),
($t$Canva$t$, $t$Ferramenta de design gráfico online, com modelos prontos para criar artes para redes sociais, apresentações e materiais impressos.$t$, $t$Criar posts para redes sociais, capas de e-book, apresentações, cartões de visita, logotipos simples e outros materiais visuais.$t$, 'iniciante', true, 'design', $t$https://www.canva.com$t$, $t$Respeite os direitos autorais de imagens e fontes ao usar elementos fora da biblioteca gratuita, e confira as licenças de uso comercial antes de utilizar um modelo.$t$),
($t$Perplexity$t$, $t$Motor de busca com IA que responde perguntas com base em fontes da internet, citando as referências utilizadas.$t$, $t$Pesquisar informações atualizadas, tirar dúvidas com respostas embasadas em fontes, fazer buscas acadêmicas e comparar informações de diferentes sites.$t$, 'iniciante', true, 'pesquisa', $t$https://www.perplexity.ai$t$, $t$Sempre confira as fontes citadas antes de considerar uma informação como verdadeira, pois nem todas as fontes são confiáveis.$t$);

-- =========================================================
-- Parte 3: Desafio de 7 dias
-- =========================================================
insert into public.challenge_days (day_number, title, description, task, goal, prompt_text) values
(1, $t$Conheça as ferramentas$t$, $t$Hoje é o seu primeiro contato oficial com a Inteligência Artificial dentro do desafio. A ideia é perder o medo de errar e entender, na prática, como funciona uma conversa com uma IA. Diferente do que muita gente pensa, não existe pergunta boba: quanto mais você experimenta, mais natural fica interagir com essas ferramentas. Escolha uma IA de texto, como ChatGPT, Gemini ou Claude, e explore livremente. Pergunte sobre temas do seu trabalho, curiosidades pessoais, dúvidas do dia a dia ou até ideias para o seu negócio. Observe como as respostas mudam quando você detalha melhor o que precisa. Esse exercício vai te dar confiança para os próximos dias do desafio, onde você vai aprender a conduzir essas conversas de forma cada vez mais estratégica. O importante hoje não é a qualidade das respostas, e sim a quantidade de perguntas diferentes que você consegue fazer.$t$, $t$Escolha uma ferramenta de IA (como ChatGPT, Gemini ou Claude) e faça pelo menos 10 perguntas diferentes sobre assuntos do seu dia a dia, trabalho ou curiosidades. Anote o que mais chamou sua atenção nas respostas.$t$, $t$Fazer pelo menos 10 perguntas diferentes para uma IA.$t$, $t$Você é um assistente de IA. Estou conhecendo a inteligência artificial pela primeira vez. Me explique, de forma simples, o que você é capaz de fazer e me dê 5 exemplos de como posso usar você no meu dia a dia de [área/profissão].$t$),
(2, $t$Aprenda a escrever prompts$t$, $t$Agora que você já perdeu a timidez de conversar com a IA, é hora de aprender a arte de escrever bons prompts. Um prompt é simplesmente a instrução que você dá para a IA, e quanto mais claro e completo ele for, melhor será o resultado. Um bom prompt geralmente informa o papel que a IA deve assumir, o assunto, o público-alvo, o objetivo e o tom de voz desejado. Hoje você vai praticar essa estrutura criando cinco prompts completos sobre temas que sejam úteis para você, seja para o trabalho, seus estudos ou um projeto pessoal. Teste cada um deles em uma ferramenta de IA e compare os resultados com perguntas mais simples e diretas que você fez no primeiro dia. Você vai perceber uma diferença enorme na qualidade das respostas. Esse é um dos aprendizados mais valiosos de todo o desafio.$t$, $t$Escreva cinco prompts completos, cada um explicando o papel da IA, o tema, o público, o objetivo e o tom desejado. Teste cada prompt em uma ferramenta de IA e observe os resultados.$t$, $t$Criar cinco prompts completos.$t$, $t$Você é um especialista em [área de conhecimento]. Preciso de ajuda com [tarefa específica], para [público ou finalidade]. O resultado deve ter um tom [tom de voz] e considerar [detalhe importante]. Apresente a resposta em [formato desejado].$t$),
(3, $t$Escolha um caminho$t$, $t$Com a IA já sendo uma aliada nas suas conversas, chegou o momento de direcionar essa energia para um objetivo concreto. Muita gente tem várias ideias na cabeça, mas nunca sai do lugar por tentar fazer tudo ao mesmo tempo. Hoje o convite é simples: escolha apenas um projeto para desenvolver até o final do desafio. Pode ser um produto digital, um serviço que você já presta, um conteúdo para redes sociais ou até a atualização do seu currículo. O segredo é escolher algo que seja viável dentro do tempo que você tem disponível nos próximos dias. Use a IA como uma parceira nessa decisão, pedindo para ela te ajudar a avaliar prós e contras de cada ideia. Definir um único caminho é o que vai te permitir avançar de verdade, em vez de ficar apenas planejando sem sair do papel.$t$, $t$Entre as ideias que você já tem (produto digital, serviço, conteúdo, currículo, etc.), escolha apenas um projeto para focar durante o restante do desafio. Escreva em poucas frases o que é esse projeto e por que você o escolheu.$t$, $t$Definir apenas um projeto.$t$, $t$Você é um mentor de projetos. Tenho as seguintes ideias: [listar ideias]. Meu tempo e recursos disponíveis são [tempo/recursos]. Ajude-me a escolher apenas uma ideia para começar, considerando viabilidade, meu interesse e o tempo que tenho disponível. Explique o motivo da escolha.$t$),
(4, $t$Crie sua primeira versão$t$, $t$Chegou a hora de tirar a ideia do papel. Hoje você vai usar a IA para criar a primeira versão do seu projeto, seja um texto, uma legenda, um roteiro, um e-book ou uma proposta de serviço. O objetivo não é criar algo perfeito, e sim ter um material concreto para trabalhar em cima. Muitas pessoas travam justamente na primeira versão, esperando que ela já saia pronta, mas o processo criativo funciona melhor quando você constrói um rascunho e depois vai refinando. Use os prompts que aprendeu a montar no Dia 2, sendo bem específico sobre o que você precisa, para que a IA te entregue um material próximo do que você imagina. Ao final do dia, você deve ter concluído esse primeiro rascunho, mesmo que ele ainda precise de ajustes nos próximos passos do desafio.$t$, $t$Use a IA para te ajudar a criar a primeira versão (rascunho) do seu projeto escolhido no Dia 3. Não se preocupe com perfeição, o objetivo é ter algo concreto nas mãos.$t$, $t$Concluir o primeiro rascunho.$t$, $t$Você é um especialista em [área relacionada ao projeto]. Me ajude a criar a primeira versão de [descrever o projeto], considerando o público [público-alvo] e o objetivo de [objetivo principal]. Estruture o conteúdo em tópicos para eu revisar e ajustar depois.$t$),
(5, $t$Deixe tudo mais profissional$t$, $t$Com o rascunho em mãos, hoje o foco é lapidar o seu projeto para que ele pareça mais profissional. Isso envolve revisar o texto em busca de erros, melhorar a organização das ideias e, se fizer sentido, cuidar também da parte visual, usando ferramentas como o Canva para criar imagens, capas ou artes que acompanhem o seu material. Pequenos detalhes fazem grande diferença na forma como o seu projeto é percebido pelas outras pessoas. Peça para a IA revisar seu texto, sugerir melhorias de clareza e apontar trechos que podem ficar mais objetivos. Aproveite também para organizar tudo em um único lugar, seja um documento, uma pasta ou uma apresentação, para facilitar o próximo passo do desafio, que é mostrar esse trabalho para alguém de fora.$t$, $t$Revise o rascunho criado no Dia 4, corrija erros, melhore a organização e, se necessário, use ferramentas de design como o Canva para deixar o material visualmente mais profissional.$t$, $t$Organizar e revisar o material.$t$, $t$Você é um revisor profissional de textos. Revise o texto a seguir, corrija erros de gramática e ortografia, melhore a clareza e a organização das ideias, mantendo o meu estilo: [colar texto do rascunho].$t$),
(6, $t$Compartilhe$t$, $t$Nenhum projeto se desenvolve isolado, e receber a opinião de outras pessoas é uma etapa fundamental antes de dar o passo final. Hoje você vai compartilhar o material que criou com alguém de confiança, pode ser um amigo, familiar, colega de trabalho ou até uma comunidade online, e pedir uma opinião sincera. O objetivo não é ouvir apenas elogios, mas entender o que pode ser melhorado antes de apresentar o projeto para um público maior. Você também pode usar a IA como uma simulação de público, pedindo para ela avaliar seu material como se fosse a pessoa que você quer atingir. Anote os pontos levantados, sem levar as críticas para o lado pessoal, e use-as como combustível para os ajustes finais que vai fazer amanhã, no último dia do desafio.$t$, $t$Compartilhe seu projeto com pelo menos uma pessoa de confiança (amigo, familiar ou colega) e peça uma opinião sincera sobre pontos fortes e pontos que podem melhorar.$t$, $t$Receber uma opinião sincera.$t$, $t$Você é um especialista em feedback construtivo. Vou te apresentar o meu projeto: [descrever o projeto]. Aja como se fosse meu público-alvo e me dê uma opinião sincera, apontando pontos fortes e sugestões de melhoria.$t$),
(7, $t$Dê o primeiro passo$t$, $t$Chegou o último dia do desafio, e ele é sobre coragem: colocar o seu projeto para fora. Depois de todo o processo de criação, revisão e feedback, é hora de publicar seu conteúdo, apresentar seu serviço para um possível cliente ou oferecer o seu produto para as primeiras pessoas. Esse passo costuma gerar receio, mas é exatamente ele que separa quem só planeja de quem coloca em prática. Não existe momento perfeito nem versão 100% pronta, e tudo bem começar de forma simples. Use os ajustes que fez com base no feedback do dia anterior e dê esse passo hoje, mesmo que pareça pequeno. O mais importante não é o resultado imediato, mas o hábito de aprender fazendo e usar a IA como aliada em cada etapa desse processo.$t$, $t$Com base no feedback recebido no Dia 6, faça os últimos ajustes e dê o passo final: publique seu conteúdo, apresente seu serviço ou ofereça seu produto para pelo menos uma pessoa ou em um canal público.$t$, $t$Publicar, apresentar ou oferecer o projeto.$t$, $t$Você é um especialista em lançamentos. Me ajude a criar uma mensagem para apresentar/publicar/oferecer o projeto [descrever o projeto] para [público-alvo], destacando os principais benefícios e incluindo uma chamada para ação clara.$t$);
